### ISSUE TITLE
有这么一个专业有爱、妹子多的团队

### ISSUE THREAD

**Issue by lifesinger** [lifesinger/lifesinger.github.com#201]
支付宝，一个马总舍不得打包上市的公司
体验技术部，一个立志成为最具专业、有爱的团队

在这里，我们追求互联网的快速、自由、乐于分享
也追求金融体系的专业、严谨、高可用性

CEO 彭蕾说，我们最大的特点是混搭风
混搭里充满纠结，但也充满机遇、挑战、颠覆

我们玩 Javascript、也玩 Java
我们写 Node、也写 C++
我们喜欢开源：Sea.js、spm、Arale、Alice、totoro、node-hsf…… 

我们玩技术、也玩设计
我们追求技术与设计的完美结合

我们多个方向急需人才：

- 前端工程师
- 交互设计师
- 视觉设计师
- Node 工程师
- Java 工程师

学历不限，层级不限，从 P5 到 P15
只要是优秀的你，我们全收，数量不限

欢迎随时与我联系
第一时间安排沟通，过程绝对保密

> 简历投递邮箱：yubo@alipay.com

我们的愿景是做地球上最具互联网性、创新性、专业有爱的团队
最后，我们团队的妹子「臻」的很多，不信在下图中仔细找找……

![](https://i.alipayobjects.com/e/201402/272sZQTcIf.jpg)

**Comment by S112** [comment]
现在还招吗？

**Comment by S112** [comment]
现在还招吗？

**Comment by lovexy-W** [comment]
请问大大们。今年还招人不？(☆_☆)/~~

**Comment by lifesinger** [comment]
一直在招的，简历发送给我就行：yubo@alipay.com

**Comment by sunny2255** [comment]
其实看了半天不知道是哪个部门额。。读研狗路过

**Comment by TaXueWWL** [comment]
用issue做博客真是个不错的想法

**Comment by ssdr** [comment]
:+1:

**Comment by cddcdd** [comment]
本科毕业生来秒杀你们了

**Comment by M2shad0w** [comment]
玉伯求推~

**Comment by jsw0528** [comment]
@M2shad0w 

简历发送到  i@mrzhang.me

**Comment by xutiancheng** [comment]
支付宝，我相中你了。

**Comment by caidewu** [comment]
P15应该是超神吧，多隆？

**Comment by RockHong** [comment]
:+1: , :+1: , :+1:

**Comment by Joozo** [comment]
!

**Comment by j717273419** [comment]
![952955198a3c502217bca764aa5e9936](https://cloud.githubusercontent.com/assets/2731580/6842188/ed892d2c-d3cf-11e4-9068-4afaf733dfe1.jpg)

**Comment by kaiynu** [comment]
niubi

**Comment by xclouds** [comment]
支付宝首页里埋的这个链接是招聘广告？

**Comment by aa1000777** [comment]
求图求真像

**Comment by dev4java** [comment]
一定是第二个

**Comment by kisnows** [comment]
潜心修炼一年，一年后去试试。

**Comment by neil-php** [comment]
![bfc243a3gw1es3jsk2dscg20aa06ix6p](https://cloud.githubusercontent.com/assets/11404005/7928663/66b6cf52-0926-11e5-983a-c678c36870e0.gif)

**Comment by suntenday** [comment]
看上去是个相当不错的团队啊，我喜欢在一个好的团队里奋斗，在HS做了一年J2EE，做了一年的Android，不过经验还是需要积累

**Comment by kbqncf** [comment]
p15。。。

**Comment by LingYanSi** [comment]
再修炼一年，过去试试

**Comment by AvenDaiyanbao** [comment]
5P-15P都可以

**Comment by Justinidlerz** [comment]
请问到年末乃至下年的考虑可否？去年末曾经在开发ATIT，做过部分优化，开发UEditor中的@功能，BUT。。因为个人原因离职了。现在的我又是一个更加优秀的我。。不过还需在异地呆完今年方可前往，不知各位大牛还会否收留。。

**Comment by lifesinger** [comment]
@Justinidlerz 随时欢迎回来，可以先发我简历 yubo@alipay.com

**Comment by chenbaof** [comment]
留名

**Comment by jackton** [comment]
招聘啊

**Comment by luqin** [comment]
妹子太少，不去！哈哈

**Comment by Hdwinqi** [comment]
现在能力 还比较渣 等我 一定要去！！！

**Comment by ArloZ** [comment]
评论很精彩

**Comment by shaonq** [comment]
支付宝提供的技术支持真的很少，国内的技术讨论圈子为何这么渣(o-o)

**Comment by wangpin34** [comment]
看起来不错。:)

**Comment by tangdaizheng** [comment]
666

**Comment by Namuhann** [comment]
一颗读博的心，走上了测试开发的不归路，然而前端才是真爱，努力中~

**Comment by Joozo** [comment]
。。。

**Comment by IssacSix** [comment]
评论很精彩
