### ISSUE TITLE
希望大家推荐一下git中有什么适合大学生做的开源项目哈

### ISSUE THREAD

**Issue by panhainan** [lifesinger/lifesinger.github.com#207]
本人目前大三，学了Struts2,Spring,Hibernate，使用过Mybatis3+SpringMVC+Spring和SSH开发过一些项目，但是感觉自己做的项目不是很能拿得出手，所以想试着在git上找找开源项目一起参与进去，希望大家给点意见哈

**Comment by Jayin** [comment]
同学，你连git和github的关系都么有搞清楚 >..<

**Comment by panhainan** [comment]
抱歉哈，打快了

**Comment by panhainan** [comment]
为什么我的问题被关了呢

**Comment by lovexy-W** [comment]
= =

**Comment by yujiangshui** [comment]
@panhainan 这是人家的博客，不是用来提问题的。

**Comment by panhainan** [comment]
抱歉了，之前没搞懂
