### ISSUE TITLE
蚂蚁与阿里

### ISSUE THREAD

**Issue by lifesinger** [lifesinger/lifesinger.github.com#211]
![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHkCQiaCeOHHomP6EUt75v3wWEHIyR3rux81uOD0an01PhGibjFqXpvEN9Q/640?wx_fmt=jpeg&tp=webp&wxfrom=5)

每次介绍自己来自蚂蚁金服，而不是阿里巴巴集团时，听者大都一脸茫然。可是我就是较真呀，干脆写篇文章。

2008年入职淘宝后，在文二路的西湖国际大厦，办公区域经常能看到可爱的蚂蚁装饰。

![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHkhjyqGW8kIfsF6pzNQItyjOmgcldYutdC9xd51h4MJ9Y4WUIbFSlTUg/640?wx_fmt=png&tp=webp&wxfrom=5)

非常有活力的蚂蚁形象，与淘宝的员工状态很搭。马总说平凡人做非凡事，就这么通过一只只小蚂蚁深入人心。

![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHk9cq8bCVLIqud3liahGN8hHUc0XEpyAeUEI6coPldhwvYMZctLsUBZ6A/640?wx_fmt=png&tp=webp&wxfrom=5)

上面这张图是蚂蚁版的射雕也叫玉伯头像，嘿嘿。

蚂蚁淘小宝很好代表了淘宝员工，但并不适合用来担当淘宝的对外品牌形象。于是，2010年9月10日淘宝年会上，淘公仔华丽丽亮相。

![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHkl0te8vq7XpXo8oq0MQbUcicxpMmjhZ7ZHDpaKNXRASDbWibicfU0HYC4w/640?wx_fmt=png&tp=webp&wxfrom=5)

拿话筒的是三通，说这款淘公仔充满时尚的设计感，浑身透着健康、阳光的橙色，与淘宝的年轻化形象非常吻合。坐在遥远的台下的我，只记得那黄黄的大型淘公仔旁边，站着一位高高的美女花名叫奇灵。这是我们身边的设计女神呀，淘宝旺旺表情、淘小宝蚂蚁形象、淘公仔初始形象，全出自她之手。

淘公仔蛮成功。我喜欢的几套要么是非卖品，要么是稀缺货。在阿里，判断一个人是否壕，可以看看办公桌上的淘公仔数量。像我这种空空如也的，除了自黑就没啥可得瑟的了-.-

![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHkcK8HPbUF3ibjk01ODft9O9B9JlicHMO8qdvrTsS7WwuZia7AKCf5Kqq6w/640?wx_fmt=png&tp=webp&wxfrom=5)

很喜欢各种淘公仔，但买不起呀，我这榆木脑袋只好继续欣赏调皮的蚂蚁。

![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHk415MzwwHV09OoUjYnDOnyIzYhZGCjicfKxhd0De5NhvibevZCqLJw1Cw/640?wx_fmt=png&tp=webp&wxfrom=5)

人的一生有时很难预判未来。我怎么也没想到，自己最终选择了离开女神云集的淘宝 UED。几经折腾，2012年来到了支付宝。

支付宝在万塘路18号，很吉利的地名，经常有狮子出没。

![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHkQCRJ4FNoOybAUk1YaWlXgXmTuuUVic9IRbRxFItuAGqItWwr2KaxfXg/640?wx_fmt=png&tp=webp&wxfrom=5)

这头狮子叫盾盾，是支付宝的吉祥物。与淘公仔相比，盾盾的形象好锉，一夜从 Uber 回到路边打车的感觉。

好在后来的故事，越来越高大上。2014年10月16日，支付宝背后的小微金服集团，正式以蚂蚁金服之名成立，这是独立于阿里巴巴集团的另一个集团。很多外界的人不信，可这事由不得信不信，无论是从法律上还是实际公司运作上，蚂蚁金服集团与阿里巴巴集团都是互相独立的，只是之间有大量兄弟般的战略合作。

![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHkGpn3U9N1OaScPSuCByFib1BDcJ3pDHZrLEIdWsHePfLHSbaGPPCnpIw/640?wx_fmt=png&tp=webp&wxfrom=5)

我亲爱的心爱的日思夜寐的魂牵梦萦的蚂蚁，就这么穿着蓝色衣服回来啦。

阿里巴巴集团与蚂蚁金服集团各有各的愿景。阿里巴巴是让天下没有难做的生意，专注于电商。蚂蚁金服是让信用等于财富，专注于金融。支付宝与蚂蚁金服的关系，就如淘宝与阿里巴巴一样。除了淘宝，阿里巴巴还有天猫、聚划算、阿里云、菜鸟等等。除了支付宝，蚂蚁金服还有余额宝、招财宝、蚂蚁微贷、芝麻信用、网商银行等等。

![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHkVGPnUvOynxSOjfIInflZ34SkL15AHZMticUKAECoaH3jrVMsZib5aTicg/640?wx_fmt=png&tp=webp&wxfrom=5)

阿里巴巴与蚂蚁金服可以统称为大阿里。最大的相同点是，一群有情有义的人快乐地共同做一件有价值有意义的事。人这一辈子，活着的意义，无非就是一些人，无非就是一些事。选择一家公司，也就是选择了一种人生观。话题突然沉重起来，就此打住。

不忘初心，怀念下最开始的蚂蚁。

![](http://mmbiz.qpic.cn/mmbiz/DFAV2KytcbUq1NrqYJUncEcbguuYMrHkrE2updCVuqEIrw3w0yExfZOBvjZ8QtJxW6LRCqA4B5XwcV1LsEJdlw/640?wx_fmt=png&tp=webp&wxfrom=5)

玉伯
2015.5.4  武汉东湖

---
欢迎关注「探索时间」，探索有趣的事，遇见有趣的人。
![](https://t.alipayobjects.com/tfscom/T1YlRfXndXXXXXXXXX.jpg)
（可以扫描二维码，也可以微信上搜索 tansuo-time 关注）

**Comment by lichunqiang** [comment]
沙发

**Comment by hotoo** [comment]
> 除了淘宝，阿里巴巴还有天猫、聚划算、阿里云、菜鸟等等。除了支付宝，蚂蚁金服还有余额宝、招财宝、蚂蚁微贷、芝麻信用、网商银行等等。

这段话用图来表达应该更清晰。

**Comment by chaoren1641** [comment]
菜鸟应该是跟阿里巴巴 ，蚂蚁金服平级的公司吧，不隶属于阿里巴巴。

在 2015年5月5日 下午1:23，闲耘™ <notifications@github.com>写道：

> 除了淘宝，阿里巴巴还有天猫、聚划算、阿里云、菜鸟等等。除了支付宝，蚂蚁金服还有余额宝、招财宝、蚂蚁微贷、芝麻信用、网商银行等等。
>
> 这段话用图来表达应该更清晰。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lifesinger/lifesinger.github.com/issues/211#issuecomment-98954122>
> .
>



-- 
*sfsdf*

**Comment by lifesinger** [comment]
@chaoren1641 菜鸟目前还属于阿里巴巴集团，未来可能会独立出来。

**Comment by markyun** [comment]
蚂蚁金服还在招前端开发人员么？

**Comment by jsw0528** [comment]
招，只要你足够靠谱。

**Comment by hkongm** [comment]
兄弟公司，金服会单独上市么

**Comment by canvs** [comment]
没看出有什么联系

**Comment by niuworld** [comment]
图片都看不到诶

**Comment by wonderfan** [comment]
@lifesinger ,把奇灵搞到手了？

**Comment by linchen1987** [comment]
选择一家公司，也就是选择了一种人生观。

**Comment by tangyefei** [comment]
很多人只是选择了一个饭碗，哪来价值观。

2015-06-18 7:45 GMT+08:00 linchen1987 <notifications@github.com>:

**Comment by CeresY** [comment]
看样子蚂蚁最近要上市了

**Comment by ZhangShuangV** [comment]
求勾搭...

**Comment by wonderfan** [comment]
any girl here?

**Comment by ourai** [comment]
@wonderfan 你是来约*的吗？

**Comment by wonderfan** [comment]
coding and dating together.
