### ISSUE TITLE
怎么弄这个博客的

### ISSUE THREAD

**Issue by wsdjeg** [lifesinger/lifesinger.github.com#217]
这个博客怎么别人液可以写

**Comment by hunkxia** [comment]
提交合并啊，github上的blog，本质上它还是认为是版本管理，所以当别人进行，修改提交申请，然后再合并嘞～

**Comment by hunkxia** [comment]
提交合并啊，github上的blog，本质上它还是认为是版本管理，所以当别人进行，修改提交申请，然后再合并嘞～
