### ISSUE TITLE
test

### ISSUE THREAD

**Issue by cshijiel** [lifesinger/lifesinger.github.com#222]
不好意思，打扰到大家了，不知道怎么删除。

**Comment by cshijiel** [comment]
怎么删除

**Comment by KyleNixLee** [comment]
edit [Title] & [comment] --> 新的issue

**Comment by hotoo** [comment]
妈蛋能不要乱提 Issue 么，这是人家的博客。

不知道怎么用 Issue 去你自己的仓库测试去。

**Comment by cshijiel** [comment]
@hotoo ... 已经关闭，抱歉。
